---
# tasks file for cobalt_strike role

# Setup/install task
- include_tasks: "windows-setup-cobaltstrike.yml"
  when: ansible_os_family == "Windows"
  
- name: Include Cobalt Strike role specific variables
  include_vars: "main.yml"

- name: Include tasks for Cobalt Strike role Teamserver or Operator
  include_tasks: "configure-{{ cobalt_strike_role }}.yml"
  tags: always

# Cleanup
- name: Delete Cobalt Strike tarballs
  file:
    path: "/tmp/*.tgz"
    state: absent
